name: language_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  animated_button: ^0.2.0
  get: ^3.24.0
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  badges: ^2.0.0-nullsafety.1
  flutter_svg: ^0.22.0
  speech_to_text: ^6.1.0
  avatar_glow: ^2.0.1
  http: ^0.13.5
#  flutter_svg: ^2.0.7
#  websafe_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/folklore/
    - assets/images/characters/
    - assets/images/homeCategory/
    - assets/icons/
#    - https://azaliacollege.000webhostapp.com/assets/folklore/
#    - https://azaliacollege.000webhostapp.com/assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Javanese
      fonts:
        - asset: assets/fonts/Javanese-Text.ttf
